name: KSAPDismiss
options:
  bundleIdPrefix: com.hxd
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  defaultConfig: Debug

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.6.0"

configs:
  Debug: debug
  Release: release

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: KSAPDismiss/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.hxd.ksapdismiss
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  KSAPDismiss:
    type: application
    platform: macOS
    sources:
      - path: KSAPDismiss
        excludes:
          - "Resources/*.xcstrings"
    resources:
      - path: KSAPDismiss/Resources/Assets.xcassets
        type: file
      - path: KSAPDismiss/Resources/en.lproj
        type: folder
      - path: KSAPDismiss/Resources/vi.lproj
        type: folder
    dependencies:
      - target: KSAPDismissHelper
      - package: Sparkle
    postCompileScripts:
      - name: Embed Privileged Helper
        script: |
          # Create LaunchServices directory
          HELPER_DIR="${TARGET_BUILD_DIR}/${WRAPPER_NAME}/Contents/Library/LaunchServices"
          mkdir -p "$HELPER_DIR"

          # Copy helper binary
          HELPER_PATH="${BUILT_PRODUCTS_DIR}/com.hxd.ksapdismiss.helper"
          if [ -f "$HELPER_PATH" ]; then
            cp "$HELPER_PATH" "$HELPER_DIR/"
            echo "Helper embedded at: $HELPER_DIR/com.hxd.ksapdismiss.helper"
          else
            echo "warning: Helper not found at $HELPER_PATH"
          fi
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_NAME: "KSAP Dismiss"
        PRODUCT_MODULE_NAME: KSAPDismiss
        PRODUCT_BUNDLE_IDENTIFIER: com.hxd.ksapdismiss
        INFOPLIST_FILE: KSAPDismiss/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: KSAPDismiss/KSAPDismiss.entitlements
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: NO
        COMBINE_HIDPI_IMAGES: YES
        CURRENT_PROJECT_VERSION: "1"
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        MARKETING_VERSION: "1.0.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.9"
    scheme:
      testTargets:
        - KSAPDismissTests
      gatherCoverageData: true

  KSAPDismissTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
      - path: KSAPDismiss
        excludes:
          - "Resources/*"
          - "KSAPDismissApp.swift"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hxd.ksapdismiss.tests
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
        PRODUCT_MODULE_NAME: KSAPDismissTests

  KSAPDismissHelper:
    type: tool
    platform: macOS
    sources:
      - path: Helper
        excludes:
          - "launchd.plist"
    settings:
      base:
        PRODUCT_NAME: com.hxd.ksapdismiss.helper
        PRODUCT_BUNDLE_IDENTIFIER: com.hxd.ksapdismiss.helper
        INFOPLIST_FILE: Helper/Info.plist
        CODE_SIGN_ENTITLEMENTS: Helper/Helper.entitlements
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: NO
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
        SKIP_INSTALL: YES
        INSTALL_PATH: /Library/PrivilegedHelperTools
        GENERATE_INFOPLIST_FILE: NO
