name: KSAPDismiss
options:
  bundleIdPrefix: com.hxd
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  defaultConfig: Debug

configs:
  Debug: debug
  Release: release

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: KSAPDismiss/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.hxd.ksapdismiss
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  KSAPDismiss:
    type: application
    platform: macOS
    sources:
      - path: KSAPDismiss
        excludes:
          - "Resources/*.xcstrings"
    resources:
      - path: KSAPDismiss/Resources/Assets.xcassets
        type: file
      - path: KSAPDismiss/Resources/en.lproj
        type: folder
      - path: KSAPDismiss/Resources/vi.lproj
        type: folder
    settings:
      base:
        PRODUCT_NAME: "KSAP Dismiss"
        PRODUCT_BUNDLE_IDENTIFIER: com.hxd.ksapdismiss
        INFOPLIST_FILE: KSAPDismiss/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_ALLOWED: NO
        COMBINE_HIDPI_IMAGES: YES
        CURRENT_PROJECT_VERSION: "1"
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        MARKETING_VERSION: "1.0.0"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.9"
    scheme:
      testTargets:
        - KSAPDismissTests
      gatherCoverageData: true

  KSAPDismissTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: KSAPDismiss
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hxd.ksapdismiss.tests
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
